### ISSUE TITLE
Can't find build-parser

### ISSUE THREAD

**Issue by Fauntleroy** [joeatwork/santas-labyrinth#1]
I want to submit a pull request to help with the build process, but I can't find `build-parser` anywhere, and `yarn build-parser` does nothing. Is the readme out of date?

**Comment by joeatwork** [comment]
It *is* out of date - there is now a hand-rolled parser in src/grammar/parser. Also *I LOVE THAT YOU'RE PLAYING WITH THIS!*, I'll try to get master into a stable state and start working on a branch.

**Comment by joeatwork** [comment]
Updated the readme in f98eb309e771c200e2c5ff88dab4c18e9bd8281c

**Comment by joeatwork** [comment]
Hey Tim, check out docs/RobotVirtualMachine.md for the (also slightly out of date) best Docs that exist so far for this lil guy

**Comment by Fauntleroy** [comment]
Hijacking the thread just to say:

It was fun! I have no idea what I'm doing, but if you need any help let me know! React / CRA are things I know way better than any person should.
